---
title: "GiottoDB"
output: rmarkdown::html_vignette
vignette: >
  %\VignetteIndexEntry{Overview}
  %\VignetteEngine{knitr::rmarkdown}
  %\VignetteEncoding{UTF-8}
---

```{r, include = FALSE}
knitr::opts_chunk$set(
  collapse = TRUE,
  comment = "#>"
)
```
## Overview
`GiottoDB` is a module in the [Giotto Suite ecosystem](https://drieslab.github.io/Giotto_website/articles/ecosystem.html) that provides database support for core `Giotto` functionality through the [dbverse](https://github.com/dbverse-org/).

## GiottoDB function support
The following functions from Giotto are supported by `GiottoDB` objects:

The following `GiottoDB` functions from `Giotto Suite` are backed by `dbverse` objects:

| Category                        | Function                                                                                                       | Status       |
|----------------------------------|---------------------------------------------------------------------------------------------------------------|--------------|
| **Subcellular Workflow**         |                                                                                                               |              |
|                                  | [GiottoClass::createGiottoPoints](https://drieslab.github.io/GiottoClass/reference/createGiottoPoints.html)    | ✅           |
|                                  | [GiottoClass::createGiottoPolygon](https://drieslab.github.io/GiottoClass/reference/createGiottoPolygon.html)  | ✅           |
|                                  | [GiottoClass::calculateOverlap](https://drieslab.github.io/GiottoClass/reference/calculateOverlap.html)        | ✅           |
|                                  | [GiottoClass::overlapToMatrix](https://drieslab.github.io/GiottoClass/reference/overlapToMatrix.html)          | ✅           |
| **Expression Data Processing**   |                                                                                                               |              |
|                                  | [GiottoClass::createExprObj](https://drieslab.github.io/GiottoClass/reference/createExprObj.html)              | ✅           |
|                                  | [GiottoClass::getExpression](https://drieslab.github.io/GiottoClass/reference/getExpression.html)              | ✅           |
|                                  | [Giotto::filterGiotto](https://drieslab.github.io/Giotto_website/reference/filterGiotto.html)                  | ✅           |
|                                  | [Giotto::processExpression](https://drieslab.github.io/Giotto_website/reference/processExpression.html)        | ✅           |
|                                  | [Giotto::normalizeGiotto](https://drieslab.github.io/Giotto_website/reference/normalizeGiotto.html)            | ✅           |
|                                  | [Giotto::addStatistics](https://drieslab.github.io/Giotto_website/reference/addStatistics.html)                | ✅           |
|                                  | [Giotto::calculateHVF](https://drieslab.github.io/Giotto_website/reference/calculateHVF.html)                  | ✅           |
| **Visualizations**               |                                                                                                               |              |
|                                  | [spatPlot2D](https://drieslab.github.io/GiottoVisuals/reference/spatPlot.html)                                 | In Progress  |
|                                  | [spatInSituPlotPoints](https://drieslab.github.io/GiottoVisuals/reference/spatInSituPlotPoints.html)           | In Progress  |

## Performance
Benchmark can be found at the [benchmarks vignette](path/to/benchmarks).
