---
title: "Overview"
output: rmarkdown::html_vignette
vignette: >
  %\VignetteIndexEntry{Overview}
  %\VignetteEngine{knitr::rmarkdown}
  %\VignetteEncoding{UTF-8}
---

```{r, include = FALSE}
knitr::opts_chunk$set(
  collapse = TRUE,
  comment = "#>"
)
```
## Overview
`GiottoDB` is a module in the [Giotto Suite ecosystem](https://drieslab.github.io/Giotto_website/articles/ecosystem.html) that provides database support for core `Giotto` functionality through the [dbverse](https://github.com/drieslab).

[overview.png](/path/to/overview.png){fig.align='center'}

## GiottoDB function support
The following non-exhaustive list of functions show which core `Giotto` functions are supported by `GiottoDB` objects:

#### Constructors
- [x] `GiottoDB()` - Create database-backed Giotto object
- [x] `as_giottodb()` - Convert giotto to GiottoDB

#### Saving and Loading
- [x] `saveGiotto()` - Save GiottoDB with database files
- [x] `loadGiotto()` - Load saved GiottoDB object

#### Subcellular
- [x] [createGiottoPoints()](https://drieslab.github.io/GiottoClass/reference/createGiottoPoints.html)
- [x] [createGiottoPolygon()](https://drieslab.github.io/GiottoClass/reference/createGiottoPolygon.html)
- [x] [calculateOverlap()](https://drieslab.github.io/GiottoClass/reference/calculateOverlap.html)
- [x] [overlapToMatrix()](https://drieslab.github.io/GiottoClass/reference/overlapToMatrix.html)
- [x] [tessellate()](https://drieslab.github.io/GiottoClass/reference/tessellate.html) - Generate hex/square tessellations

#### Expression
- [x] [createExprObj()](https://drieslab.github.io/GiottoClass/reference/createExprObj.html)
- [x] [getExpression()](https://drieslab.github.io/GiottoClass/reference/getExpression.html)
- [x] [filterGiotto()](https://drieslab.github.io/Giotto_website/reference/filterGiotto.html)
- [x] [processExpression()](https://drieslab.github.io/Giotto_website/reference/processExpression.html)
- [x] [normalizeGiotto()](https://drieslab.github.io/Giotto_website/reference/normalizeGiotto.html)
- [x] [addStatistics()](https://drieslab.github.io/Giotto_website/reference/addStatistics.html)
- [x] [calculateHVF()](https://drieslab.github.io/Giotto_website/reference/calculateHVF.html)

#### Dimension Reduction
- [x] `runPCA()` - PCA via streaming SVD and support for BPCells::svds()
- [x] `runUMAP()` - UMAP embedding (inherited)

#### Clustering
- [x] [doLeidenCluster()](https://giottosuite.com/reference/doLeidenCluster.html)
- [x] [doLeidenClusterIgraph()](https://giottosuite.com/reference/doLeidenClusterIgraph.html)

#### Visualization
- [x] `spatPlot2D()` - Spatial 2D plots
- [x] `spatInSituPlotPoints()` - In situ points visualization
- [x] `plotPCA()` - PCA scatter plots
- [x] `plotUMAP()` - UMAP scatter plots

## Dynamic Method Dispatch
While `GiottoDB` provides scalable database-backed methods of core `Giotto` functions, it does not natively support all of Giotto's functionality.

## Performance
Benchmark can be found at the [benchmarks vignette](path/to/benchmarks).
