#' Generate R code for S3 generic and methods
#'
#' @param fun_name Name of the function (string) e.g. "spatInSituPlotPoints"
#' @param pkg_name Package where the original function lives e.g. "GiottoVisuals"
#' @return A character string containing the R code
#' @keywords internal
#' @noRd
generate_viz_s3_code <- function(fun_name, pkg_name = "GiottoVisuals") {
  sprintf('
#\' Plot in situ points with GiottoDB support
#\'
#\' @description
#\' S3 wrapper for `%2$s::%1$s()` that converts dbSpatial-backed spatial slots to
#\' in-memory spatial objects before plotting.
#\'
#\' @param gobject A giotto or GiottoDB object.
#\' @param ... Additional arguments passed to `%2$s::%1$s()`.
#\' @return A ggplot object or plot object returned by `%2$s::%1$s()`.
#\' @concept Visualization
#\' @export
%1$s <- function(gobject, ...) {
  UseMethod("%1$s")
}

#\' @rdname %1$s
#\' @export
%1$s.giotto <- function(gobject, ...) {
  %2$s::%1$s(gobject = gobject, ...)
}

#\' @rdname %1$s
#\' @export
%1$s.GiottoDB <- function(gobject, ...) {
  # Cast database-backed spatial objects (dbSpatial) to terra::vect()
  gobject <- .cast_polygons_for_viz(gobject)
  gobject <- .cast_points_for_viz(gobject)
  
  %2$s::%1$s(gobject = gobject, ...)
}
', fun_name, pkg_name)
}

#' Write generated visualization code to file
#'
#' Only spatInSituPlotPoints needs S3 dispatch because it must cast dbSpatial
#' objects to terra::vect(). Other viz functions (plotPCA, plotUMAP, spatPlot2D)
#' work directly via GiottoVisuals since GiottoDB inherits from giotto.
#'
#' @param output_file Path to output file
#' @keywords internal
#' @noRd
write_viz_autogen <- function(output_file = "R/viz_autogen.R") {
  content <- c(
    "# Generated by R/viz_factory.R",
    "# Do not edit manually",
    "#",
    "# Only spatInSituPlotPoints needs a custom .GiottoDB method to cast dbSpatial objects.",
    "# Other viz functions (plotPCA, plotUMAP, spatPlot2D) work directly via GiottoVisuals",
    "# since GiottoDB inherits from giotto.",
    "",
    generate_viz_s3_code("spatInSituPlotPoints")
  )

  writeLines(content, output_file)
  message("Generated ", output_file)
}
