#' Generate R code for S3 generic and methods
#'
#' @param fun_name Name of the function (string) e.g. "spatPlot2D"
#' @param pkg_name Package where the original function lives e.g. "GiottoVisuals"
#' @return A character string containing the R code
generate_viz_s3_code <- function(fun_name, pkg_name = "GiottoVisuals") {
  # Template for the Generic
  generic_code <- sprintf(
    '
#\' @export
%s <- function(gobject, ...) {
  UseMethod("%s")
}
',
    fun_name,
    fun_name
  )

  # Template for the giotto Method (Pass-through)
  giotto_method_code <- sprintf(
    "
#' @export
%s.giotto <- function(gobject, ...) {
  %s::%s(gobject = gobject, ...)
}
",
    fun_name,
    pkg_name,
    fun_name
  )

  # Template for the GiottoDB Method (Switch Logic)
  db_method_code <- sprintf(
    '
#\' @export
%s.GiottoDB <- function(gobject, plot_method = c("deckgl", "mosaic"), ...) {
  plot_method <- match.arg(plot_method)

  internal_fun_name <- paste0(".", "%s", "_", plot_method)

  if (exists(internal_fun_name, mode = "function")) {
    internal_fun <- get(internal_fun_name, mode = "function")
    return(internal_fun(gobject = gobject, ...))
  } else {
    stop(sprintf("Backend \'%%s\' not implemented for %s", plot_method))
  }
}
',
    fun_name,
    fun_name,
    fun_name
  )

  return(paste(generic_code, giotto_method_code, db_method_code, sep = "\n"))
}

#' Write generated visualization code to file
#'
#' @param output_file Path to output file
#' @export
write_viz_autogen <- function(output_file = "R/viz_autogen.R") {
  target_functions <- c(
    "spatPlot2D",
    "spatInSituPlotPoints",
    "plotUMAP",
    "plotPCA"
  )

  # Header
  content <- c(
    "# Generated by R/viz_factory.R",
    "# Do not edit manually",
    ""
  )

  for (fun in target_functions) {
    content <- c(content, generate_viz_s3_code(fun))
  }

  writeLines(content, output_file)
  message("Generated ", output_file)
}
