# Generated by R/viz_factory.R
# Do not edit manually
#

#' @export
spatInSituPlotPoints <- function(gobject, ...) {
  UseMethod("spatInSituPlotPoints")
}

#' @export
spatInSituPlotPoints.giotto <- function(gobject, ...) {
  GiottoVisuals::spatInSituPlotPoints(gobject = gobject, ...)
}

#' @export
spatInSituPlotPoints.GiottoDB <- function(gobject, ...) {
  # Cast database-backed spatial objects (dbSpatial) to terra::vect()
  gobject <- .cast_polygons_for_viz(gobject)
  gobject <- .cast_points_for_viz(gobject)
  
  GiottoVisuals::spatInSituPlotPoints(gobject = gobject, ...)
}
