# Generated by R/viz_factory.R
# Do not edit manually


#' @export
spatPlot2D <- function(gobject, ...) {
  UseMethod("spatPlot2D")
}


#' @export
spatPlot2D.giotto <- function(gobject, ...) {
  GiottoVisuals::spatPlot2D(gobject = gobject, ...)
}


#' @export
spatPlot2D.GiottoDB <- function(gobject, plot_method = c("deckgl", "mosaic"), ...) {
  plot_method <- match.arg(plot_method)

  internal_fun_name <- paste0(".", "spatPlot2D", "_", plot_method)

  if (exists(internal_fun_name, mode = "function")) {
    internal_fun <- get(internal_fun_name, mode = "function")
    return(internal_fun(gobject = gobject, ...))
  } else {
    stop(sprintf("Backend '%s' not implemented for spatPlot2D", plot_method))
  }
}


#' @export
spatInSituPlotPoints <- function(gobject, ...) {
  UseMethod("spatInSituPlotPoints")
}


#' @export
spatInSituPlotPoints.giotto <- function(gobject, ...) {
  GiottoVisuals::spatInSituPlotPoints(gobject = gobject, ...)
}


#' @export
spatInSituPlotPoints.GiottoDB <- function(gobject, plot_method = c("deckgl", "mosaic"), ...) {
  plot_method <- match.arg(plot_method)

  internal_fun_name <- paste0(".", "spatInSituPlotPoints", "_", plot_method)

  if (exists(internal_fun_name, mode = "function")) {
    internal_fun <- get(internal_fun_name, mode = "function")
    return(internal_fun(gobject = gobject, ...))
  } else {
    stop(sprintf("Backend '%s' not implemented for spatInSituPlotPoints", plot_method))
  }
}


#' @export
plotUMAP <- function(gobject, ...) {
  UseMethod("plotUMAP")
}


#' @export
plotUMAP.giotto <- function(gobject, ...) {
  GiottoVisuals::plotUMAP(gobject = gobject, ...)
}


#' @export
plotUMAP.GiottoDB <- function(gobject, plot_method = c("deckgl", "mosaic"), ...) {
  plot_method <- match.arg(plot_method)

  internal_fun_name <- paste0(".", "plotUMAP", "_", plot_method)

  if (exists(internal_fun_name, mode = "function")) {
    internal_fun <- get(internal_fun_name, mode = "function")
    return(internal_fun(gobject = gobject, ...))
  } else {
    stop(sprintf("Backend '%s' not implemented for plotUMAP", plot_method))
  }
}


#' @export
plotUMAP_2D <- function(gobject, ...) {
  UseMethod("plotUMAP_2D")
}


#' @export
plotUMAP_2D.giotto <- function(gobject, ...) {
  GiottoVisuals::plotUMAP_2D(gobject = gobject, ...)
}


#' @export
plotUMAP_2D.GiottoDB <- function(gobject, plot_method = c("deckgl", "mosaic"), ...) {
  plot_method <- match.arg(plot_method)

  internal_fun_name <- paste0(".", "plotUMAP_2D", "_", plot_method)

  if (exists(internal_fun_name, mode = "function")) {
    internal_fun <- get(internal_fun_name, mode = "function")
    return(internal_fun(gobject = gobject, ...))
  } else {
    stop(sprintf("Backend '%s' not implemented for plotUMAP_2D", plot_method))
  }
}


#' @export
plotPCA <- function(gobject, ...) {
  UseMethod("plotPCA")
}


#' @export
plotPCA.giotto <- function(gobject, ...) {
  GiottoVisuals::plotPCA(gobject = gobject, ...)
}


#' @export
plotPCA.GiottoDB <- function(gobject, plot_method = c("deckgl", "mosaic"), ...) {
  plot_method <- match.arg(plot_method)

  internal_fun_name <- paste0(".", "plotPCA", "_", plot_method)

  if (exists(internal_fun_name, mode = "function")) {
    internal_fun <- get(internal_fun_name, mode = "function")
    return(internal_fun(gobject = gobject, ...))
  } else {
    stop(sprintf("Backend '%s' not implemented for plotPCA", plot_method))
  }
}


#' @export
plotPCA_2D <- function(gobject, ...) {
  UseMethod("plotPCA_2D")
}


#' @export
plotPCA_2D.giotto <- function(gobject, ...) {
  GiottoVisuals::plotPCA_2D(gobject = gobject, ...)
}


#' @export
plotPCA_2D.GiottoDB <- function(gobject, plot_method = c("deckgl", "mosaic"), ...) {
  plot_method <- match.arg(plot_method)

  internal_fun_name <- paste0(".", "plotPCA_2D", "_", plot_method)

  if (exists(internal_fun_name, mode = "function")) {
    internal_fun <- get(internal_fun_name, mode = "function")
    return(internal_fun(gobject = gobject, ...))
  } else {
    stop(sprintf("Backend '%s' not implemented for plotPCA_2D", plot_method))
  }
}

